name = "gabeczkaweb-authorization"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[vars]
GITHUB_CLIENT_ID = "Iv23limKstWLUxYHjNeN"
INSTALLATION_ID = "4594045"
WORKER_URL = "https://gabeczkag-github-io.gabeczkaweb-authorization.workers.dev"
SITE_ORIGIN = "https://gabeczkag.github.io"

# Wartości wrażliwe (secret) ustaw w Cloudflare -> Workers & Pages -> gabeczkaweb-auth -> Settings -> Variables and Secrets:
#   GITHUB_APP_ID
#   GITHUB_CLIENT_SECRET
#   GITHUB_PRIVATE_KEY   (klucz PKCS#8 PEM)
#   SESSION_SECRET
